const EXTENSION_MAP: Record<string, string> = {
  ts: 'typescript',
  tsx: 'typescript',
  js: 'javascript',
  jsx: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  mts: 'typescript',
  cts: 'typescript',
  json: 'json',
  jsonc: 'json',
  md: 'markdown',
  markdown: 'markdown',
  mdx: 'markdown',
  yml: 'yaml',
  yaml: 'yaml',
  toml: 'ini',
  css: 'css',
  scss: 'scss',
  less: 'less',
  html: 'html',
  htm: 'html',
  handlebars: 'handlebars',
  hbs: 'handlebars',
  xml: 'xml',
  svg: 'xml',
  py: 'python',
  rb: 'ruby',
  rs: 'rust',
  go: 'go',
  java: 'java',
  kt: 'kotlin',
  swift: 'swift',
  c: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  h: 'c',
  hpp: 'cpp',
  cs: 'csharp',
  dart: 'dart',
  php: 'php',
  r: 'r',
  sql: 'sql',
  sh: 'shell',
  bash: 'shell',
  zsh: 'shell',
  fish: 'shell',
  ps1: 'powershell',
  pl: 'perl',
  lua: 'lua',
  elm: 'elm',
  clj: 'clojure',
  cljs: 'clojure',
  erl: 'erlang',
  ex: 'elixir',
  exs: 'elixir',
  hs: 'haskell',
  ml: 'ocaml',
  graphql: 'graphql',
  gql: 'graphql',
  proto: 'protobuf',
  dockerfile: 'dockerfile',
  makefile: 'makefile',
  cmake: 'cmake',
  ini: 'ini',
  cfg: 'ini',
  conf: 'ini',
  gradle: 'ini',
  txt: 'plaintext',
  log: 'plaintext',
  diff: 'diff',
  patch: 'diff',
};

export function extensionForLanguage(filePath: string): string {
  const base = filePath.split('/').pop() ?? filePath;
  const lower = base.toLowerCase();
  if (lower === 'dockerfile') return 'dockerfile';
  if (lower === 'makefile') return 'makefile';
  if (lower === '.gitignore' || lower === '.gitattributes') return 'plaintext';
  const dot = filePath.lastIndexOf('.');
  if (dot === -1) return 'plaintext';
  const ext = filePath.slice(dot + 1).toLowerCase();
  return EXTENSION_MAP[ext] ?? 'plaintext';
}
